# -*- coding: utf-8 -*-
"""funciones_externas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qe9ZeE6vLwP_O_V0t7r3QvBX44vuudsT
"""

# more funciones_externas.py
# declaracion de funciones

#Funcion sin parametro
def funcion1():
  #Contenido de la funcion
  prin('Llamaste a la funcion 1')

#Funcion con parametros y retorno
def funcion2(a,b):
  #contenido de la funcion
  c=int(a)+int(b)
  return c