# -*- coding: utf-8 -*-
"""llamado_de_funciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T_awCZiKT3eXN9azJzsK_0JOQxLqyth6
"""

# more llamado_de_funciones.py
# Llamamos las funciones declaras en el otro archivo
from funciones_externas import *

#invocamos las funciones
funcion1()
#invocamos la otra funcion
q=input('Introduzca un dato: ')
w=input('Introduzca otro dato: ')
print(funcion2(q,w))
#